language: node_js
node_js:
  - "node"

branches:
  only:
  - master

after_success:
  - git clone https://github.com/una-club/una-newsletter.git repo
  - mkdir repo/history/
  - mv history/* repo/history/
  - cd repo
  - git config user.email mickael.a.tardy@gmail.com
  - git config user.name mickaeltardy
  - git add history/*
  - git commit -m "Publish newsletter from built"
  - git push "https://${GITHUB_TOKEN}@github.com/una-club/una-newsletter.git  > /dev/null 2>&1
